name: Pull request checks ğŸ”

on:
  pull_request:

jobs:
  unit-tests:
    name: Unit tests ğŸ
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodeVersion: ["24.x", "25.x"]

    steps:
      - name: Unit tests ğŸ
        uses: tchoupinax/repo-config/shared-actions/steps/node/test-unit@78b69c320bad96a160747ec8d6e966ad85eb63a5
        with:
          nodeVersion: ${{ matrix.nodeVersion }}
          command: "test"

  build:
    name: Check build success ğŸ¦«
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodeVersion: ["24.x", "25.x"]

    steps:
      - name: Check build success ğŸ¦«
        uses: tchoupinax/repo-config/shared-actions/steps/node/build@78b69c320bad96a160747ec8d6e966ad85eb63a5
        with:
          nodeVersion: ${{ matrix.nodeVersion }}

  labels:
    name: Autodetect labels ğŸ”
    runs-on: ubuntu-latest
    steps:
      - name: Autodetect labels ğŸ”
        uses: tchoupinax/repo-config/shared-actions/steps/dx/automatically-apply-labels@v0
        with:
          appId: ${{ secrets.DEPLOY_APP_ID }}
          privateKey: ${{ secrets.DEPLOY_APP_KEY }}

  lint:
    name: Check code quality ğŸ«†
    runs-on: ubuntu-latest
    steps:
      - name: Check code quality ğŸ«†
        uses: tchoupinax/repo-config/shared-actions/steps/golang/golangci@v0
