name: Pull request checks ğŸ”

on:
  pull_request:

jobs:
  unit-tests:
    name: Unit tests ğŸ
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodeVersion: ["24.x", "25.x"]

    steps:
      - name: Unit tests ğŸ
        uses: tchoupinax/repo-config/shared-actions/steps/node/test-unit@0eab8e54a30e8885c850658efb5bcad5d13c38ce
        with:
          nodeVersion: ${{ matrix.nodeVersion }}
  build:
    name: Check build success ğŸ¦«
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodeVersion: ["24.x", "25.x"]

    steps:
      - name: Check build success ğŸ¦«
        uses: tchoupinax/repo-config/shared-actions/steps/node/build@0eab8e54a30e8885c850658efb5bcad5d13c38ce
        with:
          nodeVersion: ${{ matrix.nodeVersion }}
